name: Build and Deploy ratings microservice to Development

on:
  push:
    branches-ignore:
      - 'main'   

  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  deploy:
    uses: robot-shop-DevOps/robot-shop-github-actions/.github/workflows/microservices-php.yaml@main
    with:
      MICROSERVICE: ratings
      IMAGE: ratings
      NAMESPACE: ratings-microservice
      RELEASE: ratings
      WORKING_DIR: ./ratings/html
      DOCKERFILE_PATH: ./ratings
    secrets: inherit